name: Continious Integration

on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display Node.js version
        run: node --version

      - name: Display npm version
        run: npm --version

      # Ajoutez d'autres commandes pour afficher des informations utiles

      - name: Install dependencies
        run: npm install

      - name: Clear Node.js and npm cache
        run: npm cache clean -f


      - name: 'Publish to NPM'
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_SECRET }}
